# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc998ddae3155acd6965a063ecf6a86abaa557ddfae4ed337abb09aacc4a396503fa5bc3f0bd43fd9829bec7f48944dafd40a1cf8c97cb15f3e88386428f0421

test:
  secret_key_base: 37c4d59275ad637cee52761e81394d910f7792eaa248e0e18849f87255d95a87bbe9c200f3243e026240e6356d00cbe0136cb79fa05afa310e6f2c7d32c36a88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
